name: Subgraph CI/CD

on:
  pull_request:
    branches: [main]
    paths:
      - 'pop-subgraph/**'
      - 'peer-cashoutrelay-base/**'
  push:
    branches: [main]
    paths:
      - 'pop-subgraph/**'
      - 'peer-cashoutrelay-base/**'

jobs:
  subgraph-arbitrum-one:
    uses: BreadchainCoop/subgraphform/.github/workflows/_subgraph-cicd.yml@hudsonhrh/add-network-input
    with:
      subgraph-name: poa-arb-v-1
      working-directory: pop-subgraph
      network: arbitrum-one
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  subgraph-gnosis:
    uses: BreadchainCoop/subgraphform/.github/workflows/_subgraph-cicd.yml@hudsonhrh/add-network-input
    with:
      subgraph-name: poa-gnosis-v-1
      working-directory: pop-subgraph
      network: gnosis
      run-tests: false
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  subgraph-base:
    uses: BreadchainCoop/subgraphform/.github/workflows/_subgraph-cicd.yml@hudsonhrh/add-network-input
    with:
      subgraph-name: peer-cashoutrelay-base
      working-directory: peer-cashoutrelay-base
      network: base
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
